import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.page}>
      <Head>
        <title> styled-lib</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <div className={styles.logo}>logo</div>
        <div className={styles.login}>login</div>
      </div>

      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.items_navbar}>
            <h2>Logins</h2>
            <Link href="/logins/1" as={`/logins/1`}>
              <a>
                <h3>login form 1</h3>
              </a>
            </Link>

            <Link href="/logins/2" as={`/logins/2`}>
              <a>
                <h3>login form 2</h3>
              </a>
            </Link>
            <Link href="/logins/3" as={`/logins/3`}>
              <a>
                <h3>login form 3</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>Register forms</h2>
            <Link href="/register/1" as={`/register/1`}>
              <a>
                <h3>Register1</h3>
              </a>
            </Link>

            <Link href="/register/2" as={`/register1/2`}>
              <a>
                <h3>Register2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
          <div className={styles.items_navbar}>
            <h2>navbars</h2>
            <Link href="/navbars/1" as={`/navbars/1`}>
              <a>
                <h3>navbar1</h3>
              </a>
            </Link>

            <Link href="/navbars/2" as={`/navbars/2`}>
              <a>
                <h3>navbar2</h3>
              </a>
            </Link>
          </div>
        </main>
        <footer className={styles.footer}>
          <div>
            <h3>
              <span>Powered by ch {new Date().getFullYear()}</span>
            </h3>
          </div>
        </footer>
      </div>
    </div>
  );
}
